cats99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats
end

cats99/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats99/app/models/cat.rb
class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper

  validates :birth_date, presence: true
  validates :color, presence: true, inclusion: { in: ['White', 'Black', 'Brown', 'Orange']}
  validates :name, presence: true
  validates :sex, presence: true, inclusion: { in: ['M', 'F']}
  validates :description, presence: true

  def age(birth_date)
    time_ago_in_words(birth_date)
  end
end

cats99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index 
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages, status: 422
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])

    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render json: @cat.errors.full_messages, status: 422
    end

  end

  private
  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end
end

cats99/app/helpers/application_helper.rb
module ApplicationHelper
end

cats99/app/helpers/cats_helper.rb
module CatsHelper
end

cats99/app/views/cats/edit.html.erb
<form action="<%= cat_url(@cat) %>" method="post">
  <input type = "hidden" name="_method" value="patch">
  <label for= "name">Name:
    <input type = "text" id="name" name="cat[name]" value="<%=@cat.name%>">
  </label>
  <br>
  <label for= "birth_date">Birth_date:
    <input type = "date" id="birth_date" name="cat[birth_date]" value="<%=@cat.birth_date%>">
  </label>
  <br>
  <label for= "cat_color">Color:
    <select name="cat[color]" id="cat_color">
      <option selected= "selected">
      <%=@cat.color%>
      </option>
      <option>-----</option>
      <option value="White">White</option>
      <option value="Black">Black</option>
      <option value="Brown">Brown</option>
      <option value="Orange">Orange</option>
    </select>

  </label>
  <br>
  <label for= "sex">Sex:
    <% if @cat.sex == "M" %>
    <input type = "radio" name="cat[sex]" value="M" checked = "">M
    <input type = "radio" name="cat[sex]" value="F">F
    <% else %>
    <input type = "radio" name="cat[sex]" value="M">M
    <input type = "radio" name="cat[sex]" value="F" checked = "">F
    <% end %>
  </label>
  <br>
  <label for= "description">Description:
    <textarea id="description" name="cat[description]"><%=@cat.description%></textarea>
  </label>
  <br>
  <input type="submit" value="Create Cat">
</form>

cats99/app/views/cats/index.html.erb
<ul>
  <% @cats.each do |cat| %>
  <li>
    <ul>
      <li><%= cat.birth_date %></li>
      <li><%= cat.color %></li>
      <li><%= cat.name %></li>
      <li><%= cat.sex %></li>
      <li><%= cat.description %></li>
    </ul>
  </li>
  <% end %>
</ul>

cats99/app/views/cats/new.html.erb
<form action="<%= cats_url %>" method="post">
  <label for= "name">Name:
    <input type = "text" id="name" name="cat[name]">
  </label>
  <br>
  <label for= "birth_date">Birth_date:
    <input type = "date" id="birth_date" name="cat[birth_date]">
  </label>
  <br>
  <label for= "cat_color">Color:
    <select name="cat[color]" id="cat_color">
      <option>-----</option>
      <option value="White">White</option>
      <option value="Black">Black</option>
      <option value="Brown">Brown</option>
      <option value="Orange">Orange</option>
    </select>

  </label>
  <br>
  <label for= "sex">Sex:
    <input type = "radio" name="cat[sex]" value="M">M
    <input type = "radio" name="cat[sex]" value="F">F
  </label>
  <br>
  <label for= "description">Description:
    <textarea id="description" name="cat[description]"></textarea>
  </label>
  <br>
  <input type="submit" value="Create Cat">
</form>

cats99/app/views/cats/show.html.erb
<table>
    <thead>
        <tr>
            <th colspan="2">Cat Attributes</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Name</td>
            <td>Color</td>
            <td>Birth_Date</td>
            <td>Sex</td>
            <td>Descritpion</td>
        </tr>
         <tr>
            <td><%= @cat.name %></td>
            <td><%= @cat.color %></td>
            <td><%= @cat.birth_date %></td>
            <td><%= @cat.sex %></td>
            <td><%= @cat.description %></td>
        </tr>
    </tbody>
</table>

cats99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>